### ISSUE TITLE
Release of training code

### ISSUE THREAD

**Issue by shlomig123** [mandiant/stringsifter#33] opened 2023-06-25 08:36 UTC
Hey, 
Since your project is no longer supported properly, I was wondering if you would reconsider releasing the training code, as you have considered to do so in the past, as noted under Discussion in your README:
_"Please note that neither labeled data nor training code is currently available, though we may reconsider this approach in future releases."_
It would also be very helpful if in addition to the training code you would have released the labeled data used to train it as well.

**Comment by ewalshmndt** [comment] 2023-07-13 16:26
Duplicate of #4

**Closed by ewalshmndt** 2023-07-13 16:26 UTC
